#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'apache2', '>= 1.0.0'
cookbook 'mysql'
cookbook 'database'
cookbook 'php'
cookbook 'vagrant_magento',
  :git => 'https://github.com/rjocoleman/vagrant_magento'